export const symptoms = {
  head: [
    { id: 's_21', label: 'Headache' },
    { id: 's_478', label: 'Face pain' },
    { id: 's_1436', label: 'Sinus pain or pressure' },
    { id: 's_98', label: 'Fever' },
    { id: 's_616', label: 'Swollen face' },
    { id: 's_1156', label: 'Facial muscle weakness' },
    { id: 's_971', label: 'Face numbness' },
    { id: 's_1543', label: 'Loss of consciousness' },
    { id: 's_316', label: 'Impaired memory' },
    { id: 's_370', label: 'Dizzy' },
    { id: 's_156', label: 'Feeling sick or queasy' },
    { id: 's_121', label: 'Hair loss' },
    { id: 's_1808', label: 'Skin changes located on the face' },
  ],
  ears: [
    { id: 's_47', label: 'Earache' },
    { id: 's_208', label: 'Decreased hearing' },
    { id: 's_297', label: 'Discharge from ear' },
    { id: 's_276', label: 'Clogged ear' },
    { id: 's_255', label: 'Itching in ear' },
    { id: 's_407', label: 'Ringing in ears' },
  ],
  eyes: [
    { id: 's_493', label: 'Eye pain' },
    { id: 's_492', label: 'Bloodshot eye' },
    { id: 's_72', label: 'Red and stinging eyes' },
    { id: 's_1563', label: 'Itching of eyes' },
    { id: 's_122', label: 'Watery eyes' },
    { id: 's_1492', label: 'Yellow eyes' },
    { id: 's_54', label: 'Pain near eye socket' },
    { id: 's_320', label: 'Impaired vision' },
    { id: 's_207', label: 'Double vision' },
    { id: 's_1465', label: 'Temporary blindness' },
    { id: 's_497', label: 'Asymmetric pupils' },
    { id: 's_483', label: 'Skin changes on eyelid' },
    { id: 's_1442', label: 'Swelling around the eyes' },
    { id: 's_192', label: 'Drooping eyelids' },
    { id: 's_489', label: 'Dry discharge on eyelids' },
    { id: 's_606', label: 'Eye flashes' },
    { id: 's_488', label: 'Light sensitivity' },
  ],
  nose: [
    { id: 's_1605', label: 'Nose pain' },
    { id: 's_1996', label: 'Swollen nose' },
    { id: 's_107', label: 'Runny nose' },
    { id: 's_331', label: 'Stuffed nose' },
    { id: 's_252', label: 'Itchy throat or nose' },
    { id: 's_1303', label: 'Nasal voice' },
    { id: 's_67', label: 'Snoring' },
    { id: 's_715', label: 'Sneezing' },
    { id: 's_1095', label: 'Difficulty smelling' },
    { id: 's_1436', label: 'Sinus pain or pressure' },
    { id: 's_1429', label: 'Bleeding from nose' },
    { id: 's_1471', label: 'Mucus dripping at the back of the throat' },
  ],
  oral_cavity: [
    { id: 's_694', label: 'Dermatological changes inside the mouth' },
    { id: 's_65', label: 'Bad breath' },
    { id: 's_247', label: 'Dry mouth' },
    { id: 's_551', label: 'Toothache' },
    { id: 's_266', label: 'Difficulty biting and chewing' },
    { id: 's_19', label: 'Gum pain' },
    { id: 's_172', label: 'Swollen gums' },
    { id: 's_111', label: 'Bleeding gums' },
    { id: 's_607', label: 'Unusually red tongue' },
    { id: 's_200', label: 'Burning sensation on tongue' },
    { id: 's_102', label: 'Cough' },
    { id: 's_67', label: 'Snoring' },
    { id: 's_305', label: 'Vomiting' },
    { id: 's_116', label: 'Coughing up blood' },
    { id: 's_284', label: 'Diminished appetite' },
    { id: 's_310', label: 'Increased thirst' },
    { id: 's_610', label: 'White spots on tonsils' },
    { id: 's_88', label: 'Shortness of breath' },
  ],
  neck_or_throat: [
    { id: 's_67', label: 'Sore throat' },
    { id: 's_67', label: 'Painful swallowing' },
    { id: 's_67', label: 'Difficulty swallowing' },
    { id: 's_67', label: 'Red throat' },
    { id: 's_67', label: 'Cough' },
    { id: 's_67', label: 'Hawking' },
    { id: 's_67', label: 'Whistling sound made while breathing' },
    { id: 's_67', label: 'Mucus dripping at the back of the throat' },
    { id: 's_67', label: 'Hoarse voice' },
    { id: 's_67', label: 'Itchy throat or nose' },
    { id: 's_67', label: 'Shortness of breath' },
    { id: 's_67', label: 'Neck pain' },
    { id: 's_67', label: 'Enlarged lymph nodes' },
    { id: 's_67', label: 'Swollen neck' },
    { id: 's_67', label: 'Stiff neck' },
    { id: 's_67', label: 'Widened neck veins' },
  ],
  chest: [
    { id: 's_67', label: 'Breast enlargement in man' },
    { id: 's_67', label: 'Chest pain' },
    { id: 's_67', label: 'Chest pain, spreading to the left upper limb' },
    { id: 's_67', label: 'Pressing chest pain' },
    { id: 's_67', label: 'Heartburn' },
    { id: 's_67', label: 'Palpitations' },
    { id: 's_67', label: 'Fast heartbeat' },
    { id: 's_67', label: 'Slow heart rate' },
    { id: 's_67', label: 'Cough' },
    { id: 's_67', label: 'Shortness of breath' },
    { id: 's_67', label: 'Shallow breathing' },
    { id: 's_67', label: 'Accelerated breathing' },
    { id: 's_67', label: 'Whistling sound made while breathing' },
  ],
  upper_arm: [
    { id: 's_67', label: 'Pain in upper limb' },
    { id: 's_67', label: 'Severe pain in upper limb' },
    { id: 's_67', label: 'Shoulder pain' },
    { id: 's_67', label: 'Shoulder pain while moving' },
    { id: 's_67', label: 'Restricted range of joint motion' },
    { id: 's_67', label: 'Pain in both upper limbs' },
    { id: 's_67', label: 'Swelling of upper limb' },
    { id: 's_67', label: 'Swollen shoulder' },
    { id: 's_67', label: 'Numbness of one upper limb' },
    { id: 's_67', label: 'Numbeness of both upper limbs' },
    { id: 's_67', label: 'Loss of feeling in both arms' },
    { id: 's_67', label: 'Spasms in upper extrimites' },
  ],
  forearm: [
    { id: 's_67', label: 'Pain in upper limb' },
    { id: 's_67', label: 'Pain in forearm' },
    { id: 's_67', label: 'Pain in both upper limbs' },
    { id: 's_67', label: 'Severe pain in upper limb' },
    { id: 's_67', label: 'Swelling of the upper limb' },
    { id: 's_67', label: 'Swollen elbow' },
    { id: 's_67', label: 'Swollen wrist' },
    { id: 's_67', label: 'Wrist pain' },
    { id: 's_67', label: 'Wrist pain while moving' },
    { id: 's_67', label: 'Elbow pain' },
    { id: 's_67', label: 'Elbow pain when moving it' },
    { id: 's_67', label: 'Numbness of both upper limbs' },
    { id: 's_67', label: 'Dropping hand' },
    { id: 's_67', label: 'Loss of feeling in both arms' },
    { id: 's_67', label: 'Spasms in upper extremities' },
  ],
  hand: [
    { id: 's_67', label: 'Wrist pain' },
    { id: 's_67', label: 'Wrist pain while moving' },
    { id: 's_67', label: 'Pain in fingers or hand' },
    { id: 's_67', label: 'One finger pain' },
    { id: 's_67', label: 'Pain of the skin around the nail' },
    { id: 's_67', label: 'Swollen hand' },
    { id: 's_67', label: 'Swollen wrist' },
    { id: 's_67', label: 'Swollen finger' },
    { id: 's_67', label: 'Skin changes on hands' },
    { id: 's_67', label: 'Red hand' },
    { id: 's_67', label: 'Grayish-blue fingers' },
    { id: 's_67', label: 'Red skin on palms' },
    { id: 's_67', label: 'Tingling fingers' },
    { id: 's_67', label: 'Trembling of both hands' },
    { id: 's_67', label: 'Trembling of one hand' },
    { id: 's_67', label: 'Loss of muscles in hands' },
    { id: 's_67', label: 'Morning stiffness of hand joints' },
    { id: 's_67', label: 'Cold hands or fingers' },
  ],
  upper_abdomen: [
    { id: 's_67', label: 'Stomach pain' },
    { id: 's_67', label: 'Upper central stomach pain' },
    { id: 's_67', label: 'Upper left side stomach pain' },
    { id: 's_67', label: 'Upper right side stomach pain' },
    { id: 's_67', label: 'Burning or gnawing stomach pain' },
    { id: 's_67', label: 'Colic stomach pain' },
    { id: 's_67', label: 'Crampy stomach pain' },
    { id: 's_67', label: 'Sharp and stabbing stomach pain' },
    { id: 's_67', label: 'Pain when pressing the stomach' },
    { id: 's_67', label: 'Heartburn' },
    { id: 's_67', label: 'Lump in stomach' },
    { id: 's_67', label: 'Increased abdominal size' },
    { id: 's_67', label: 'Bloating' },
    { id: 's_67', label: 'Vomiting' },
    { id: 's_67', label: 'Feeling sick or queasy' },
    { id: 's_67', label: 'Indigestion' },
    { id: 's_67', label: 'Vomiting blood' },
    { id: 's_67', label: 'Weight loss' },
  ],
  middle_abdomen: [
    { id: 's_67', label: 'Stomach pain' },
    { id: 's_67', label: 'Central stomach pain' },
    { id: 's_67', label: 'Burning or gnawing stomach pain' },
    { id: 's_67', label: 'Colic stomach pain' },
    { id: 's_67', label: 'Crampy stomach pain' },
    { id: 's_67', label: 'Sharp and stabbing stomach pain' },
    { id: 's_67', label: 'Pain when pressing the stomach' },
    { id: 's_67', label: 'Lump in stomach' },
    { id: 's_67', label: 'Increased abdominal size' },
    { id: 's_67', label: 'Bloating' },
    { id: 's_67', label: 'Constipation' },
    { id: 's_67', label: 'Diarrhea' },
    { id: 's_67', label: 'Vomiting' },
    { id: 's_67', label: 'Feeling sick or queasy' },
    { id: 's_67', label: 'Black stools' },
    { id: 's_67', label: 'Blood in stool' },
  ],
  lower_abdomen: [
    { id: 's_67', label: 'Stomach pain' },
    { id: 's_67', label: 'Lower left side stomach pain' },
    { id: 's_67', label: 'Colic stomach pain' },
    { id: 's_67', label: 'Crampy stomach pain' },
    { id: 's_67', label: 'Lower right side stomach pain' },
    { id: 's_67', label: 'Lower stomach pain' },
    { id: 's_67', label: 'Sharp and stabbing stomach pain' },
    { id: 's_67', label: 'Pain when pressing the stomach' },
    { id: 's_67', label: 'Bloating' },
    { id: 's_67', label: 'Increased abdominal size' },
    { id: 's_67', label: 'Lump in stomach' },
    { id: 's_67', label: 'Loss of bowel control' },
    { id: 's_67', label: 'Constipation' },
    { id: 's_67', label: 'Diarrhea' },
    { id: 's_67', label: 'Black stools' },
    { id: 's_67', label: 'Blood in stool' },
  ],
  sexual_organs: [
    { id: 's_67', label: 'Discharge from urethra' },
    { id: 's_67', label: 'Intermittent urine flow' },
    { id: 's_67', label: 'Pain in scrotum' },
    { id: 's_67', label: 'Swollen scrotum' },
    { id: 's_67', label: 'Feeling of weight in scrotum' },
    { id: 's_67', label: 'Difference in size of testicles' },
    { id: 's_67', label: 'Lump in scrotum' },
    { id: 's_67', label: 'Erectile dysfunction' },
    { id: 's_67', label: 'Frequent urination' },
    { id: 's_67', label: 'Pain while urinating' },
    { id: 's_67', label: 'Dark urine' },
    { id: 's_67', label: 'Blood in urine' },
    { id: 's_67', label: 'Urinary incotinence' },
    { id: 's_67', label: 'Urinating at night' },
    { id: 's_67', label: 'Crotch pain' },
    { id: 's_67', label: 'Itching in crotch' },
    { id: 's_67', label: 'Urgent need to urinate' },
    { id: 's_67', label: 'Urination in small amounts' },
    { id: 's_67', label: 'Skin changes on or around genitals' },
  ],
  thigh: [
    { id: 's_67', label: 'Pain in lower limb' },
    { id: 's_67', label: 'Severe pain in lower limb' },
    { id: 's_67', label: 'Thigh pain' },
    { id: 's_67', label: 'Pain in both lower limbs' },
    { id: 's_67', label: 'Joint pain, hip' },
    { id: 's_67', label: 'Joint pain, during hip movement' },
    { id: 's_67', label: 'Lower back pain spreading to the back of the thigh or knee' },
    { id: 's_67', label: 'Limping due to pain' },
    {
      id: 's_67',
      label: 'Acute thigh or buttock pain appearing during exertion and relieving after short rest',
    },
    { id: 's_67', label: 'Pain when pressing lower limb' },
    { id: 's_67', label: 'Swollen leg' },
    { id: 's_67', label: 'Hip swelling' },
    { id: 's_67', label: 'Numbness in one lower limb' },
    { id: 's_67', label: 'Numbness of both lower limbs' },
    { id: 's_67', label: 'Red stretch marks on stomach, hips, or thighs' },
  ],
  knee: [
    { id: 's_67', label: 'Pain in lower limb' },
    { id: 's_67', label: 'Severe pain in lower limb' },
    { id: 's_67', label: 'Pain in both lower limbs' },
    { id: 's_67', label: 'Knee pain' },
    { id: 's_67', label: 'Knee pain when moving it' },
    { id: 's_67', label: 'Pain when pressing joint' },
    { id: 's_67', label: 'Stiff joints' },
    { id: 's_67', label: 'Limping due to pain' },
    { id: 's_67', label: 'Swollen knee' },
    { id: 's_67', label: 'Slower walk' },
    { id: 's_67', label: 'Creaking joints during movement' },
  ],
  lower_leg: [
    { id: 's_67', label: 'Pain in lower limb' },
    { id: 's_67', label: 'Pain in both lower limbs' },
    { id: 's_67', label: 'Severe pain in lower limb' },
    { id: 's_67', label: 'Calf pain' },
    { id: 's_67', label: 'Pain when pressing calf' },
    { id: 's_67', label: 'Severe calf pain while moving' },
    { id: 's_67', label: 'Knee pain' },
    { id: 's_67', label: 'Swollen leg' },
    { id: 's_67', label: 'Swollen legs' },
    { id: 's_67', label: 'Numbness in one lower limb' },
    { id: 's_67', label: 'Numbness of both lower limbs' },
    { id: 's_67', label: 'Cramps in calves' },
    { id: 's_67', label: 'Heavy legs at the end of the day' },
    { id: 's_67', label: 'Loss of feeling in only one arm or leg' },
  ],
  foot: [
    { id: 's_67', label: 'Foot pain' },
    { id: 's_67', label: 'Toe pain' },
    { id: 's_67', label: 'Sore nail' },
    { id: 's_67', label: 'Pain of the skin around the nail' },
    { id: 's_67', label: 'Ankle pain' },
    { id: 's_67', label: 'Big toe pain' },
    { id: 's_67', label: 'Feet tingling or numbness' },
    { id: 's_67', label: 'Swollen feet' },
    { id: 's_67', label: 'Swollen toe' },
    { id: 's_67', label: 'Skin changes on feet' },
    { id: 's_67', label: 'Thickened nails' },
    { id: 's_67', label: 'Enlarged finger tips' },
    { id: 's_67', label: 'Brown nail discolouration' },
    { id: 's_67', label: 'White nail discoloration' },
    { id: 's_67', label: 'Yellow nails' },
    { id: 's_67', label: 'Cold feets and toes' },
    { id: 's_67', label: 'Dropping the front of the foot' },
    { id: 's_67', label: 'Feet pain' },
  ],
  back: [
    { id: 's_67', label: 'Back pain' },
    { id: 's_67', label: 'Back pain that comes and goes' },
    { id: 's_67', label: 'Back pain worsening after physical activity' },
    { id: 's_67', label: 'Sudden back pain' },
    { id: 's_67', label: 'Severe back pain' },
    { id: 's_67', label: 'Middle or upper back pain' },
    { id: 's_67', label: 'Back pain decreases during rest' },
    { id: 's_67', label: 'Back pain lasting several hours' },
    { id: 's_67', label: 'Stiffness of spine in the morning' },
    { id: 's_67', label: 'Spine asymmetry' },
    { id: 's_67', label: 'Difficulty bending down' },
  ],
  elbow: [
    { id: 's_305', label: 'Pain in upper limb' },
    { id: 's_305', label: 'Severe pain in upper limb' },
    { id: 's_305', label: 'Elbow pain' },
    { id: 's_305', label: 'Elbow pain when moving it' },
    { id: 's_305', label: 'Swollen elbow' },
  ],
  lower_back: [
    { id: 's_305', label: 'Back pain' },
    { id: 's_305', label: 'Lower back pain' },
    { id: 's_305', label: 'Back pain that comes and goes' },
    { id: 's_305', label: 'Sudden back pain' },
    { id: 's_305', label: 'Severe back pain' },
    { id: 's_305', label: 'Back pain worsening after physical activity' },
    { id: 's_305', label: 'Lower back pain spreading to the groin' },
    { id: 's_305', label: 'Back pain decreases during rest' },
    { id: 's_305', label: 'Back pain lasting several hours' },
    { id: 's_305', label: 'Lower back pain spreading to the back of the thigh or knee' },
    { id: 's_305', label: 'Paraspinal muscle tenderness' },
    { id: 's_305', label: 'Difficulty bending down' },
    { id: 's_305', label: 'Stiffness of spine in the morning' },
  ],
  buttocks: [
    { id: 's_305', label: 'Buttocks pain' },
    { id: 's_305', label: 'Joint pain, hip' },
    { id: 's_305', label: 'Joint pain, during hip movement' },
    { id: 's_305', label: 'Pain in lower limb' },
    { id: 's_305', label: 'Pain in both lower limbs' },
    {
      id: 's_305',
      label: 'Acute thigh or buttock pain appearing during exertion and relieving after short rest',
    },
    { id: 's_305', label: 'Lower back pain spreading to the back of the thigh or knee' },
    { id: 's_305', label: 'Anorectal pain' },
    { id: 's_305', label: 'Hip swelling' },
    { id: 's_305', label: 'Bleeding from anus' },
    { id: 's_305', label: 'Ulcerations or abscesses near the anus' },
    { id: 's_305', label: 'Itching around anus' },
    { id: 's_305', label: 'Blood in stool' },
    { id: 's_305', label: 'Black stools' },
  ],
};
