export const symptoms = {
  head: [
    { id: 's_21', name: 'Headache' },
    { id: 's_478', name: 'Face pain' },
    { id: 's_1436', name: 'Sinus pain or pressure' },
    { id: 's_98', name: 'Fever' },
    { id: 's_616', name: 'Swollen face' },
    { id: 's_1156', name: 'Facial muscle weakness' },
    { id: 's_971', name: 'Face numbness' },
    { id: 's_1543', name: 'Loss of consciousness' },
    { id: 's_316', name: 'Impaired memory' },
    { id: 's_370', name: 'Dizzy' },
    { id: 's_156', name: 'Feeling sick or queasy' },
    { id: 's_121', name: 'Hair loss' },
    { id: 's_1808', name: 'Skin changes located on the face' },
  ],
  ears: [
    { id: 's_47', name: 'Earache' },
    { id: 's_208', name: 'Decreased hearing' },
    { id: 's_297', name: 'Discharge from ear' },
    { id: 's_276', name: 'Clogged ear' },
    { id: 's_255', name: 'Itching in ear' },
    { id: 's_407', name: 'Ringing in ears' },
  ],
  eyes: [
    { id: 's_493', name: 'Eye pain' },
    { id: 's_492', name: 'Bloodshot eye' },
    { id: 's_72', name: 'Red and stinging eyes' },
    { id: 's_1563', name: 'Itching of eyes' },
    { id: 's_122', name: 'Watery eyes' },
    { id: 's_1492', name: 'Yellow eyes' },
    { id: 's_54', name: 'Pain near eye socket' },
    { id: 's_320', name: 'Impaired vision' },
    { id: 's_207', name: 'Double vision' },
    { id: 's_1465', name: 'Temporary blindness' },
    { id: 's_497', name: 'Asymmetric pupils' },
    { id: 's_483', name: 'Skin changes on eyelid' },
    { id: 's_1442', name: 'Swelling around the eyes' },
    { id: 's_192', name: 'Drooping eyelids' },
    { id: 's_489', name: 'Dry discharge on eyelids' },
    { id: 's_606', name: 'Eye flashes' },
    { id: 's_488', name: 'Light sensitivity' },
  ],
};
