export const symptoms = {
  head: [
    { id: 's_21', label: 'Headache' },
    { id: 's_478', label: 'Face pain' },
    { id: 's_1436', label: 'Sinus pain or pressure' },
    { id: 's_98', label: 'Fever' },
    { id: 's_616', label: 'Swollen face' },
    { id: 's_1156', label: 'Facial muscle weakness' },
    { id: 's_971', label: 'Face numbness' },
    { id: 's_1543', label: 'Loss of consciousness' },
    { id: 's_316', label: 'Impaired memory' },
    { id: 's_370', label: 'Dizzy' },
    { id: 's_156', label: 'Feeling sick or queasy' },
    { id: 's_121', label: 'Hair loss' },
    { id: 's_1808', label: 'Skin changes located on the face' },
  ],
  ears: [
    { id: 's_47', label: 'Earache' },
    { id: 's_208', label: 'Decreased hearing' },
    { id: 's_297', label: 'Discharge from ear' },
    { id: 's_276', label: 'Clogged ear' },
    { id: 's_255', label: 'Itching in ear' },
    { id: 's_407', label: 'Ringing in ears' },
  ],
  eyes: [
    { id: 's_493', label: 'Eye pain' },
    { id: 's_492', label: 'Bloodshot eye' },
    { id: 's_72', label: 'Red and stinging eyes' },
    { id: 's_1563', label: 'Itching of eyes' },
    { id: 's_122', label: 'Watery eyes' },
    { id: 's_1492', label: 'Yellow eyes' },
    { id: 's_54', label: 'Pain near eye socket' },
    { id: 's_320', label: 'Impaired vision' },
    { id: 's_207', label: 'Double vision' },
    { id: 's_1465', label: 'Temporary blindness' },
    { id: 's_497', label: 'Asymmetric pupils' },
    { id: 's_483', label: 'Skin changes on eyelid' },
    { id: 's_1442', label: 'Swelling around the eyes' },
    { id: 's_192', label: 'Drooping eyelids' },
    { id: 's_489', label: 'Dry discharge on eyelids' },
    { id: 's_606', label: 'Eye flashes' },
    { id: 's_488', label: 'Light sensitivity' },
  ],
  nose: [
    { id: 's_1605', label: 'Nose pain' },
    { id: 's_1996', label: 'Swollen nose' },
    { id: 's_107', label: 'Runny nose' },
    { id: 's_331', label: 'Stuffed nose' },
    { id: 's_252', label: 'Itchy throat or nose' },
    { id: 's_1303', label: 'Nasal voice' },
    { id: 's_67', label: 'Snoring' },
    { id: 's_715', label: 'Sneezing' },
    { id: 's_1095', label: 'Difficulty smelling' },
    { id: 's_1436', label: 'Sinus pain or pressure' },
    { id: 's_1429', label: 'Bleeding from nose' },
    { id: 's_1471', label: 'Mucus dripping at the back of the throat' },
  ],
  oral_cavity: [
    { id: 's_694', label: 'Dermatological changes inside the mouth' },
    { id: 's_65', label: 'Bad breath' },
    { id: 's_247', label: 'Dry mouth' },
    { id: 's_551', label: 'Toothache' },
    { id: 's_266', label: 'Difficulty biting and chewing' },
    { id: 's_19', label: 'Gum pain' },
    { id: 's_172', label: 'Swollen gums' },
    { id: 's_111', label: 'Bleeding gums' },
    { id: 's_607', label: 'Unusually red tongue' },
    { id: 's_200', label: 'Burning sensation on tongue' },
    { id: 's_102', label: 'Cough' },
    { id: 's_67', label: 'Snoring' },
    { id: 's_305', label: 'Vomiting' },
    { id: 's_116', label: 'Coughing up blood' },
    { id: 's_284', label: 'Diminished appetite' },
    { id: 's_310', label: 'Increased thirst' },
    { id: 's_610', label: 'White spots on tonsils' },
    { id: 's_88', label: 'Shortness of breath' },
  ],
};
